#!/bin/bash
echo Please state location of scrapy project folder
read project
echo Please state the investing.com website e.g. https://www.investing.com/equities/enphase-energy-inc
read inv_website
echo Please state the yahoo website e.g. https://sg.finance.yahoo.com/quote/ENPH?p=ENPH
read yahoo_website
echo Please state the name of the output file, this will be a json file
read output_name
echo Please state the save location for the output file. Note output file will be json  e.g. /home/user/Desktop
read output_location
echo Please state the location of the chrome driver e.g. /home/user/Downloads
read driver

cd $project/$project/spiders/

scrapy crawl my-investing-spider -a inv_link=$inv_website -a yahoo_link=$yahoo_website -a driver=$driver/chromedriver -o $output_location/$output_name.json
#
